version: "3.9"
services:
  api:
    build: .
    image: crypto-agent-backend:0.2.0
    ports: ["8000:8000"]
    env_file: [".env"]
    depends_on: ["redis"]
    volumes:
      - ./data:/data
    restart: unless-stopped
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
    restart: unless-stopped
